# https://gethomepage.dev/widgets/
- greeting:
    text_size: xl
    text: Welcome home

- resources:
    label: System
    cpu: true
    memory: true
    cputemp: true
    uptime: true
    units: metric

- resources:
    label: Storage
    expanded: true
    disk:
      - /
      - /storage
      - /storage/Torrents/Movies

- search:
    provider: duckduckgo
    focus: false
    showSearchSuggestions: true
    target: _blank

- openmeteo:
    latitude: "{{HOMEPAGE_VAR_LATITUDE}}"
    longitude: "{{HOMEPAGE_VAR_LONGITUDE}}"
    timezone: "{{HOMEPAGE_VAR_TZ}}"
    units: metric
    cache: 5

- datetime:
    text_size: xl
    format:
      dateStyle: long
      timeStyle: short
      hour12: false
